from pymongo import MongoClient  # type: ignore

# MONGO_ADDRESS = os.getenv("MONGO_ADDRESS")
MONGO_ADDRESS = "mongodb://localhost:27017"

client = MongoClient(MONGO_ADDRESS)
db = client["problem-dating-app"]
users = db.users

data = [
    {
        "name": "Alex Johnson",
        "email": "alex.j@example.com",
        "linkedIn": "linkedin.com/in/alexj",
        "x": "@alexj",
        "personalWebsite": "alexj.dev",
        "gitHub": "github.com/alexj",
        "bio": "Full stack developer interested in AI and machine learning",
        "country": "United States",
        "city": "San Francisco",
        "availability": "20",
        "needHelp": True,
        "projectName": "AI Image Generator",
        "projectDescription": "Building a stable diffusion based image generation tool",
        "helpDescription": "Need help with optimizing the model and UI/UX design",
        "projectLink": "github.com/alexj/ai-image-gen",
        "timeFrame": "3 months",
        "skills": [
            "Python",
            "PyTorch",
            "React",
            "TypeScript",
            "AWS",
            "Docker",
            "Node.js",
            "PostgreSQL",
            "Redis",
            "FastAPI",
        ],
        "skillLevels": {
            "Python": 5,
            "PyTorch": 3,
            "React": 4,
            "TypeScript": 4,
            "AWS": 3,
            "Docker": 4,
            "Node.js": 4,
            "PostgreSQL": 3,
            "Redis": 2,
            "FastAPI": 4,
        },
        "themes": ["AI/ML", "Web Development"],
    },
    {
        "name": "Sarah Chen",
        "email": "sarah.c@example.com",
        "linkedIn": "linkedin.com/in/sarahc",
        "x": "@sarahcodes",
        "personalWebsite": "sarahchen.dev",
        "gitHub": "github.com/sarahc",
        "bio": "Backend developer specializing in distributed systems",
        "country": "Canada",
        "city": "Toronto",
        "availability": "15",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Go",
            "Kubernetes",
            "gRPC",
            "Cassandra",
            "Kafka",
            "Prometheus",
            "Terraform",
            "Python",
            "Java",
            "Redis",
        ],
        "skillLevels": {
            "Go": 5,
            "Kubernetes": 4,
            "gRPC": 4,
            "Cassandra": 3,
            "Kafka": 4,
            "Prometheus": 3,
            "Terraform": 4,
            "Python": 3,
            "Java": 4,
            "Redis": 3,
        },
        "themes": ["Backend", "DevOps"],
    },
    {
        "name": "Miguel Rodriguez",
        "email": "miguel.r@example.com",
        "linkedIn": "linkedin.com/in/miguelr",
        "x": "@migueldev",
        "personalWebsite": "miguelr.dev",
        "gitHub": "github.com/miguelr",
        "bio": "Mobile developer passionate about cross-platform development",
        "country": "Spain",
        "city": "Madrid",
        "availability": "25",
        "needHelp": True,
        "projectName": "Health Tracking App",
        "projectDescription": "Building a comprehensive health and fitness tracking mobile app",
        "helpDescription": "Looking for help with backend architecture and machine learning for personalized recommendations",
        "projectLink": "github.com/miguelr/health-track",
        "timeFrame": "6 months",
        "skills": [
            "Flutter",
            "Dart",
            "Firebase",
            "Swift",
            "Kotlin",
            "Node.js",
            "MongoDB",
            "TensorFlow",
            "GraphQL",
            "CI/CD",
        ],
        "skillLevels": {
            "Flutter": 5,
            "Dart": 5,
            "Firebase": 4,
            "Swift": 3,
            "Kotlin": 3,
            "Node.js": 3,
            "MongoDB": 2,
            "TensorFlow": 1,
            "GraphQL": 3,
            "CI/CD": 3,
        },
        "themes": ["Mobile Development", "Health Tech"],
    },
    {
        "name": "Emma Wilson",
        "email": "emma.w@example.com",
        "linkedIn": "linkedin.com/in/emmaw",
        "x": "@emmaw_dev",
        "personalWebsite": "emmawilson.dev",
        "gitHub": "github.com/emmaw",
        "bio": "Frontend developer focused on accessibility and user experience",
        "country": "United Kingdom",
        "city": "London",
        "availability": "30",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "React",
            "Vue.js",
            "JavaScript",
            "HTML",
            "CSS",
            "WCAG",
            "Jest",
            "Cypress",
            "Storybook",
            "Figma",
        ],
        "skillLevels": {
            "React": 5,
            "Vue.js": 4,
            "JavaScript": 5,
            "HTML": 5,
            "CSS": 5,
            "WCAG": 4,
            "Jest": 4,
            "Cypress": 3,
            "Storybook": 4,
            "Figma": 3,
        },
        "themes": ["Frontend", "Accessibility"],
    },
    {
        "name": "Raj Patel",
        "email": "raj.p@example.com",
        "linkedIn": "linkedin.com/in/rajp",
        "x": "@raj_codes",
        "personalWebsite": "rajpatel.dev",
        "gitHub": "github.com/rajp",
        "bio": "DevOps engineer specializing in cloud infrastructure",
        "country": "India",
        "city": "Bangalore",
        "availability": "20",
        "needHelp": True,
        "projectName": "Cloud Cost Optimizer",
        "projectDescription": "Developing a tool to optimize cloud resources and reduce costs",
        "helpDescription": "Need assistance with frontend development and data visualization",
        "projectLink": "github.com/rajp/cloud-optimizer",
        "timeFrame": "4 months",
        "skills": [
            "AWS",
            "Azure",
            "Terraform",
            "Ansible",
            "Docker",
            "Kubernetes",
            "Python",
            "Shell Scripting",
            "Grafana",
            "Jenkins",
        ],
        "skillLevels": {
            "AWS": 5,
            "Azure": 4,
            "Terraform": 5,
            "Ansible": 4,
            "Docker": 5,
            "Kubernetes": 4,
            "Python": 3,
            "Shell Scripting": 4,
            "Grafana": 3,
            "Jenkins": 4,
        },
        "themes": ["DevOps", "Cloud Computing"],
    },
    {
        "name": "Julia Schmidt",
        "email": "julia.s@example.com",
        "linkedIn": "linkedin.com/in/julias",
        "x": "@juliaschmidt",
        "personalWebsite": "juliaschmidt.dev",
        "gitHub": "github.com/julias",
        "bio": "Data scientist working on NLP projects",
        "country": "Germany",
        "city": "Berlin",
        "availability": "25",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "PyTorch",
            "NLTK",
            "SpaCy",
            "scikit-learn",
            "TensorFlow",
            "SQL",
            "R",
            "Docker",
            "Git",
        ],
        "skillLevels": {
            "Python": 5,
            "PyTorch": 4,
            "NLTK": 5,
            "SpaCy": 4,
            "scikit-learn": 5,
            "TensorFlow": 3,
            "SQL": 4,
            "R": 3,
            "Docker": 3,
            "Git": 4,
        },
        "themes": ["Data Science", "NLP"],
    },
    {
        "name": "Lucas Silva",
        "email": "lucas.s@example.com",
        "linkedIn": "linkedin.com/in/lucass",
        "x": "@lucasdev",
        "personalWebsite": "lucassilva.dev",
        "gitHub": "github.com/lucass",
        "bio": "Game developer with focus on VR/AR experiences",
        "country": "Brazil",
        "city": "São Paulo",
        "availability": "30",
        "needHelp": True,
        "projectName": "VR Educational Platform",
        "projectDescription": "Creating an immersive learning platform for STEM subjects",
        "helpDescription": "Need help with 3D modeling and educational content creation",
        "projectLink": "github.com/lucass/vr-edu",
        "timeFrame": "8 months",
        "skills": [
            "Unity",
            "C#",
            "Blender",
            "WebGL",
            "JavaScript",
            "Three.js",
            "React",
            "Node.js",
            "WebXR",
            "AWS",
        ],
        "skillLevels": {
            "Unity": 5,
            "C#": 4,
            "Blender": 3,
            "WebGL": 4,
            "JavaScript": 4,
            "Three.js": 3,
            "React": 3,
            "Node.js": 3,
            "WebXR": 4,
            "AWS": 2,
        },
        "themes": ["Game Development", "Education Tech"],
    },
    {
        "name": "Anna Kowalski",
        "email": "anna.k@example.com",
        "linkedIn": "linkedin.com/in/annak",
        "x": "@anna_codes",
        "personalWebsite": "annakowalski.dev",
        "gitHub": "github.com/annak",
        "bio": "Security researcher and penetration tester",
        "country": "Poland",
        "city": "Warsaw",
        "availability": "15",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "Burp Suite",
            "Wireshark",
            "Metasploit",
            "Linux",
            "Bash",
            "JavaScript",
            "SQL",
            "Docker",
            "AWS",
        ],
        "skillLevels": {
            "Python": 4,
            "Burp Suite": 5,
            "Wireshark": 5,
            "Metasploit": 4,
            "Linux": 5,
            "Bash": 4,
            "JavaScript": 3,
            "SQL": 4,
            "Docker": 3,
            "AWS": 3,
        },
        "themes": ["Security", "DevSecOps"],
    },
    {
        "name": "David Kim",
        "email": "david.k@example.com",
        "linkedIn": "linkedin.com/in/davidk",
        "x": "@davidkim_dev",
        "personalWebsite": "davidkim.dev",
        "gitHub": "github.com/davidk",
        "bio": "Blockchain developer focusing on DeFi solutions",
        "country": "South Korea",
        "city": "Seoul",
        "availability": "25",
        "needHelp": True,
        "projectName": "DeFi Lending Platform",
        "projectDescription": "Building a decentralized lending platform with novel collateral mechanisms",
        "helpDescription": "Looking for help with smart contract auditing and frontend development",
        "projectLink": "github.com/davidk/defi-lending",
        "timeFrame": "5 months",
        "skills": [
            "Solidity",
            "Web3.js",
            "React",
            "TypeScript",
            "Hardhat",
            "Python",
            "Rust",
            "Go",
            "PostgreSQL",
            "AWS",
        ],
        "skillLevels": {
            "Solidity": 5,
            "Web3.js": 4,
            "React": 3,
            "TypeScript": 3,
            "Hardhat": 4,
            "Python": 3,
            "Rust": 2,
            "Go": 3,
            "PostgreSQL": 3,
            "AWS": 2,
        },
        "themes": ["Blockchain", "DeFi"],
    },
    {
        "name": "Sofia Martinez",
        "email": "sofia.m@example.com",
        "linkedIn": "linkedin.com/in/sofiam",
        "x": "@sofiatech",
        "personalWebsite": "sofiamartinez.dev",
        "gitHub": "github.com/sofiam",
        "bio": "IoT specialist and embedded systems developer",
        "country": "Mexico",
        "city": "Mexico City",
        "availability": "20",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "C++",
            "Python",
            "Arduino",
            "Raspberry Pi",
            "MQTT",
            "Node.js",
            "AWS IoT",
            "Docker",
            "Git",
            "Linux",
        ],
        "skillLevels": {
            "C++": 5,
            "Python": 4,
            "Arduino": 5,
            "Raspberry Pi": 5,
            "MQTT": 4,
            "Node.js": 3,
            "AWS IoT": 4,
            "Docker": 3,
            "Git": 4,
            "Linux": 4,
        },
        "themes": ["IoT", "Embedded Systems"],
    },
    {
        "name": "Thomas Anderson",
        "email": "thomas.a@example.com",
        "linkedIn": "linkedin.com/in/thomasa",
        "x": "@thomas_codes",
        "personalWebsite": "thomasanderson.dev",
        "gitHub": "github.com/thomasa",
        "bio": "Systems architect specializing in microservices",
        "country": "Australia",
        "city": "Melbourne",
        "availability": "25",
        "needHelp": True,
        "projectName": "Microservices Migration Tool",
        "projectDescription": "Creating a tool to assist in monolith to microservices migration",
        "helpDescription": "Need help with service mesh implementation and documentation",
        "projectLink": "github.com/thomasa/micro-migrator",
        "timeFrame": "4 months",
        "skills": [
            "Java",
            "Spring Boot",
            "Kubernetes",
            "Docker",
            "AWS",
            "Terraform",
            "Go",
            "Python",
            "Kafka",
            "MongoDB",
        ],
        "skillLevels": {
            "Java": 5,
            "Spring Boot": 5,
            "Kubernetes": 4,
            "Docker": 4,
            "AWS": 4,
            "Terraform": 3,
            "Go": 3,
            "Python": 3,
            "Kafka": 4,
            "MongoDB": 3,
        },
        "themes": ["Microservices", "Cloud Architecture"],
    },
    {
        "name": "Lisa Wang",
        "email": "lisa.w@example.com",
        "linkedIn": "linkedin.com/in/lisaw",
        "x": "@lisawang_dev",
        "personalWebsite": "lisawang.dev",
        "gitHub": "github.com/lisaw",
        "bio": "Computer vision engineer working on autonomous systems",
        "country": "Singapore",
        "city": "Singapore",
        "availability": "30",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "OpenCV",
            "TensorFlow",
            "PyTorch",
            "C++",
            "ROS",
            "Docker",
            "Linux",
            "CUDA",
            "AWS",
        ],
        "skillLevels": {
            "Python": 5,
            "OpenCV": 5,
            "TensorFlow": 4,
            "PyTorch": 4,
            "C++": 4,
            "ROS": 3,
            "Docker": 3,
            "Linux": 4,
            "CUDA": 3,
            "AWS": 3,
        },
        "themes": ["Computer Vision", "Robotics"],
    },
    {
        "id": "google-oauth2|110412812981559470574",
        "availability": 1,
        "bio": "I like to run!",
        "city": "Boston",
        "country": "USA",
        "email": "charlienicholsonr@gmail.com",
        "gitHub": "https://github.com/crnicholson",
        "image": "https://lh3.googleusercontent.com/a/ACg8ocKO3ED4ZmQKm93I88oTosqBBn9BcJXcGS6JT4gShX2c4hQiUoU=s96-c",
        "linkedIn": "https://linkedin.com/in/crnicholson",
        "name": "Charlie Nicholson",
        "needHelp": False,
        "personalWebsite": "https://crnicholson.com",
        "skillLevels": {
            "Electrical engineering": 3,
            "Mechanical engineering": 4,
            "Python": 2,
        },
        "skills": ["Mechanical engineering", "Electrical engineering", "Python"],
        "themes": ["Art", "Business", "Design"],
        "timeFrame": "",
        "x": "",
        "pastMatches": [
            "",
            "67bb50e1f3e3bdf96fb958e7",
            "67bb50e1f3e3bdf96fb958eb",
            "67bb50e1f3e3bdf96fb958ef",
            "67bb50e1f3e3bdf96fb958f1",
        ],
    },
]

users.delete_many({})
users.insert_many(data)

print("Data inserted successfully.")

for user in users.find():
    print(user)
