from pymongo import MongoClient # type: ignore

# MONGO_ADDRESS = os.getenv("MONGO_ADDRESS")
MONGO_ADDRESS = "mongodb://localhost:27017"

client = MongoClient(MONGO_ADDRESS)
db = client["problem-dating-app"]
users = db.users

data = [
    {
        "name": "Alex Johnson",
        "email": "alex.j@example.com",
        "linkedIn": "linkedin.com/in/alexj",
        "x": "@alexj",
        "personalWebsite": "alexj.dev",
        "gitHub": "github.com/alexj",
        "bio": "Full stack developer interested in AI and machine learning",
        "country": "United States",
        "city": "San Francisco",
        "availability": "20",
        "needHelp": True,
        "projectName": "AI Image Generator",
        "projectDescription": "Building a stable diffusion based image generation tool",
        "helpDescription": "Need help with optimizing the model and UI/UX design",
        "projectLink": "github.com/alexj/ai-image-gen",
        "timeFrame": "3 months",
        "skills": [
            "Python",
            "PyTorch",
            "React",
            "TypeScript",
            "AWS",
            "Docker",
            "Node.js",
            "PostgreSQL",
            "Redis",
            "FastAPI",
        ],
        "skillLevels": [
            {"skill": "Python", "level": 5},
            {"skill": "PyTorch", "level": 3},
            {"skill": "React", "level": 4},
            {"skill": "TypeScript", "level": 4},
            {"skill": "AWS", "level": 3},
            {"skill": "Docker", "level": 4},
            {"skill": "Node.js", "level": 4},
            {"skill": "PostgreSQL", "level": 3},
            {"skill": "Redis", "level": 2},
            {"skill": "FastAPI", "level": 4},
        ],
        "themes": ["AI/ML", "Web Development"],
    },
    {
        "name": "Sarah Chen",
        "email": "sarah.c@example.com",
        "linkedIn": "linkedin.com/in/sarahc",
        "x": "@sarahcodes",
        "personalWebsite": "sarahchen.dev",
        "gitHub": "github.com/sarahc",
        "bio": "Backend developer specializing in distributed systems",
        "country": "Canada",
        "city": "Toronto",
        "availability": "15",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Go",
            "Kubernetes",
            "gRPC",
            "Cassandra",
            "Kafka",
            "Prometheus",
            "Terraform",
            "Python",
            "Java",
            "Redis",
        ],
        "skillLevels": [
            {"skill": "Go", "level": 5},
            {"skill": "Kubernetes", "level": 4},
            {"skill": "gRPC", "level": 4},
            {"skill": "Cassandra", "level": 3},
            {"skill": "Kafka", "level": 4},
            {"skill": "Prometheus", "level": 3},
            {"skill": "Terraform", "level": 4},
            {"skill": "Python", "level": 3},
            {"skill": "Java", "level": 4},
            {"skill": "Redis", "level": 3},
        ],
        "themes": ["Backend", "DevOps"],
    },
    {
        "name": "Miguel Rodriguez",
        "email": "miguel.r@example.com",
        "linkedIn": "linkedin.com/in/miguelr",
        "x": "@migueldev",
        "personalWebsite": "miguelr.dev",
        "gitHub": "github.com/miguelr",
        "bio": "Mobile developer passionate about cross-platform development",
        "country": "Spain",
        "city": "Madrid",
        "availability": "25",
        "needHelp": True,
        "projectName": "Health Tracking App",
        "projectDescription": "Building a comprehensive health and fitness tracking mobile app",
        "helpDescription": "Looking for help with backend architecture and machine learning for personalized recommendations",
        "projectLink": "github.com/miguelr/health-track",
        "timeFrame": "6 months",
        "skills": [
            "Flutter",
            "Dart",
            "Firebase",
            "Swift",
            "Kotlin",
            "Node.js",
            "MongoDB",
            "TensorFlow",
            "GraphQL",
            "CI/CD",
        ],
        "skillLevels": [
            {"skill": "Flutter", "level": 5},
            {"skill": "Dart", "level": 5},
            {"skill": "Firebase", "level": 4},
            {"skill": "Swift", "level": 3},
            {"skill": "Kotlin", "level": 3},
            {"skill": "Node.js", "level": 3},
            {"skill": "MongoDB", "level": 2},
            {"skill": "TensorFlow", "level": 1},
            {"skill": "GraphQL", "level": 3},
            {"skill": "CI/CD", "level": 3},
        ],
        "themes": ["Mobile Development", "Health Tech"],
    },
    {
        "name": "Emma Wilson",
        "email": "emma.w@example.com",
        "linkedIn": "linkedin.com/in/emmaw",
        "x": "@emmaw_dev",
        "personalWebsite": "emmawilson.dev",
        "gitHub": "github.com/emmaw",
        "bio": "Frontend developer focused on accessibility and user experience",
        "country": "United Kingdom",
        "city": "London",
        "availability": "30",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "React",
            "Vue.js",
            "JavaScript",
            "HTML",
            "CSS",
            "WCAG",
            "Jest",
            "Cypress",
            "Storybook",
            "Figma",
        ],
        "skillLevels": [
            {"skill": "React", "level": 5},
            {"skill": "Vue.js", "level": 4},
            {"skill": "JavaScript", "level": 5},
            {"skill": "HTML", "level": 5},
            {"skill": "CSS", "level": 5},
            {"skill": "WCAG", "level": 4},
            {"skill": "Jest", "level": 4},
            {"skill": "Cypress", "level": 3},
            {"skill": "Storybook", "level": 4},
            {"skill": "Figma", "level": 3},
        ],
        "themes": ["Frontend", "Accessibility"],
    },
    {
        "name": "Raj Patel",
        "email": "raj.p@example.com",
        "linkedIn": "linkedin.com/in/rajp",
        "x": "@raj_codes",
        "personalWebsite": "rajpatel.dev",
        "gitHub": "github.com/rajp",
        "bio": "DevOps engineer specializing in cloud infrastructure",
        "country": "India",
        "city": "Bangalore",
        "availability": "20",
        "needHelp": True,
        "projectName": "Cloud Cost Optimizer",
        "projectDescription": "Developing a tool to optimize cloud resources and reduce costs",
        "helpDescription": "Need assistance with frontend development and data visualization",
        "projectLink": "github.com/rajp/cloud-optimizer",
        "timeFrame": "4 months",
        "skills": [
            "AWS",
            "Azure",
            "Terraform",
            "Ansible",
            "Docker",
            "Kubernetes",
            "Python",
            "Shell Scripting",
            "Grafana",
            "Jenkins",
        ],
        "skillLevels": [
            {"skill": "AWS", "level": 5},
            {"skill": "Azure", "level": 4},
            {"skill": "Terraform", "level": 5},
            {"skill": "Ansible", "level": 4},
            {"skill": "Docker", "level": 5},
            {"skill": "Kubernetes", "level": 4},
            {"skill": "Python", "level": 3},
            {"skill": "Shell Scripting", "level": 4},
            {"skill": "Grafana", "level": 3},
            {"skill": "Jenkins", "level": 4},
        ],
        "themes": ["DevOps", "Cloud Computing"],
    },
    {
        "name": "Julia Schmidt",
        "email": "julia.s@example.com",
        "linkedIn": "linkedin.com/in/julias",
        "x": "@juliaschmidt",
        "personalWebsite": "juliaschmidt.dev",
        "gitHub": "github.com/julias",
        "bio": "Data scientist working on NLP projects",
        "country": "Germany",
        "city": "Berlin",
        "availability": "25",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "PyTorch",
            "NLTK",
            "SpaCy",
            "scikit-learn",
            "TensorFlow",
            "SQL",
            "R",
            "Docker",
            "Git",
        ],
        "skillLevels": [
            {"skill": "Python", "level": 5},
            {"skill": "PyTorch", "level": 4},
            {"skill": "NLTK", "level": 5},
            {"skill": "SpaCy", "level": 4},
            {"skill": "scikit-learn", "level": 5},
            {"skill": "TensorFlow", "level": 3},
            {"skill": "SQL", "level": 4},
            {"skill": "R", "level": 3},
            {"skill": "Docker", "level": 3},
            {"skill": "Git", "level": 4},
        ],
        "themes": ["Data Science", "NLP"],
    },
    {
        "name": "Lucas Silva",
        "email": "lucas.s@example.com",
        "linkedIn": "linkedin.com/in/lucass",
        "x": "@lucasdev",
        "personalWebsite": "lucassilva.dev",
        "gitHub": "github.com/lucass",
        "bio": "Game developer with focus on VR/AR experiences",
        "country": "Brazil",
        "city": "São Paulo",
        "availability": "30",
        "needHelp": True,
        "projectName": "VR Educational Platform",
        "projectDescription": "Creating an immersive learning platform for STEM subjects",
        "helpDescription": "Need help with 3D modeling and educational content creation",
        "projectLink": "github.com/lucass/vr-edu",
        "timeFrame": "8 months",
        "skills": [
            "Unity",
            "C#",
            "Blender",
            "WebGL",
            "JavaScript",
            "Three.js",
            "React",
            "Node.js",
            "WebXR",
            "AWS",
        ],
        "skillLevels": [
            {"skill": "Unity", "level": 5},
            {"skill": "C#", "level": 4},
            {"skill": "Blender", "level": 3},
            {"skill": "WebGL", "level": 4},
            {"skill": "JavaScript", "level": 4},
            {"skill": "Three.js", "level": 3},
            {"skill": "React", "level": 3},
            {"skill": "Node.js", "level": 3},
            {"skill": "WebXR", "level": 4},
            {"skill": "AWS", "level": 2},
        ],
        "themes": ["Game Development", "Education Tech"],
    },
    {
        "name": "Anna Kowalski",
        "email": "anna.k@example.com",
        "linkedIn": "linkedin.com/in/annak",
        "x": "@anna_codes",
        "personalWebsite": "annakowalski.dev",
        "gitHub": "github.com/annak",
        "bio": "Security researcher and penetration tester",
        "country": "Poland",
        "city": "Warsaw",
        "availability": "15",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "Burp Suite",
            "Wireshark",
            "Metasploit",
            "Linux",
            "Bash",
            "JavaScript",
            "SQL",
            "Docker",
            "AWS",
        ],
        "skillLevels": [
            {"skill": "Python", "level": 4},
            {"skill": "Burp Suite", "level": 5},
            {"skill": "Wireshark", "level": 5},
            {"skill": "Metasploit", "level": 4},
            {"skill": "Linux", "level": 5},
            {"skill": "Bash", "level": 4},
            {"skill": "JavaScript", "level": 3},
            {"skill": "SQL", "level": 4},
            {"skill": "Docker", "level": 3},
            {"skill": "AWS", "level": 3},
        ],
        "themes": ["Security", "DevSecOps"],
    },
    {
        "name": "David Kim",
        "email": "david.k@example.com",
        "linkedIn": "linkedin.com/in/davidk",
        "x": "@davidkim_dev",
        "personalWebsite": "davidkim.dev",
        "gitHub": "github.com/davidk",
        "bio": "Blockchain developer focusing on DeFi solutions",
        "country": "South Korea",
        "city": "Seoul",
        "availability": "25",
        "needHelp": True,
        "projectName": "DeFi Lending Platform",
        "projectDescription": "Building a decentralized lending platform with novel collateral mechanisms",
        "helpDescription": "Looking for help with smart contract auditing and frontend development",
        "projectLink": "github.com/davidk/defi-lending",
        "timeFrame": "5 months",
        "skills": [
            "Solidity",
            "Web3.js",
            "React",
            "TypeScript",
            "Hardhat",
            "Python",
            "Rust",
            "Go",
            "PostgreSQL",
            "AWS",
        ],
        "skillLevels": [
            {"skill": "Solidity", "level": 5},
            {"skill": "Web3.js", "level": 4},
            {"skill": "React", "level": 3},
            {"skill": "TypeScript", "level": 3},
            {"skill": "Hardhat", "level": 4},
            {"skill": "Python", "level": 3},
            {"skill": "Rust", "level": 2},
            {"skill": "Go", "level": 3},
            {"skill": "PostgreSQL", "level": 3},
            {"skill": "AWS", "level": 2},
        ],
        "themes": ["Blockchain", "DeFi"],
    },
    {
        "name": "Sofia Martinez",
        "email": "sofia.m@example.com",
        "linkedIn": "linkedin.com/in/sofiam",
        "x": "@sofiatech",
        "personalWebsite": "sofiamartinez.dev",
        "gitHub": "github.com/sofiam",
        "bio": "IoT specialist and embedded systems developer",
        "country": "Mexico",
        "city": "Mexico City",
        "availability": "20",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "C++",
            "Python",
            "Arduino",
            "Raspberry Pi",
            "MQTT",
            "Node.js",
            "AWS IoT",
            "Docker",
            "Git",
            "Linux",
        ],
        "skillLevels": [
            {"skill": "C++", "level": 5},
            {"skill": "Python", "level": 4},
            {"skill": "Arduino", "level": 5},
            {"skill": "Raspberry Pi", "level": 5},
            {"skill": "MQTT", "level": 4},
            {"skill": "Node.js", "level": 3},
            {"skill": "AWS IoT", "level": 4},
            {"skill": "Docker", "level": 3},
            {"skill": "Git", "level": 4},
            {"skill": "Linux", "level": 4},
        ],
        "themes": ["IoT", "Embedded Systems"],
    },
    {
        "name": "Thomas Anderson",
        "email": "thomas.a@example.com",
        "linkedIn": "linkedin.com/in/thomasa",
        "x": "@thomas_codes",
        "personalWebsite": "thomasanderson.dev",
        "gitHub": "github.com/thomasa",
        "bio": "Systems architect specializing in microservices",
        "country": "Australia",
        "city": "Melbourne",
        "availability": "25",
        "needHelp": True,
        "projectName": "Microservices Migration Tool",
        "projectDescription": "Creating a tool to assist in monolith to microservices migration",
        "helpDescription": "Need help with service mesh implementation and documentation",
        "projectLink": "github.com/thomasa/micro-migrator",
        "timeFrame": "4 months",
        "skills": [
            "Java",
            "Spring Boot",
            "Kubernetes",
            "Docker",
            "AWS",
            "Terraform",
            "Go",
            "Python",
            "Kafka",
            "MongoDB",
        ],
        "skillLevels": [
            {"skill": "Java", "level": 5},
            {"skill": "Spring Boot", "level": 5},
            {"skill": "Kubernetes", "level": 4},
            {"skill": "Docker", "level": 4},
            {"skill": "AWS", "level": 4},
            {"skill": "Terraform", "level": 3},
            {"skill": "Go", "level": 3},
            {"skill": "Python", "level": 3},
            {"skill": "Kafka", "level": 4},
            {"skill": "MongoDB", "level": 3},
        ],
        "themes": ["Microservices", "Cloud Architecture"],
    },
    {
        "name": "Lisa Wang",
        "email": "lisa.w@example.com",
        "linkedIn": "linkedin.com/in/lisaw",
        "x": "@lisawang_dev",
        "personalWebsite": "lisawang.dev",
        "gitHub": "github.com/lisaw",
        "bio": "Computer vision engineer working on autonomous systems",
        "country": "Singapore",
        "city": "Singapore",
        "availability": "30",
        "needHelp": False,
        "projectName": "",
        "projectDescription": "",
        "helpDescription": "",
        "projectLink": "",
        "timeFrame": "",
        "skills": [
            "Python",
            "OpenCV",
            "TensorFlow",
            "PyTorch",
            "C++",
            "ROS",
            "Docker",
            "Linux",
            "CUDA",
            "AWS",
        ],
        "skillLevels": [
            {"skill": "Python", "level": 5},
            {"skill": "OpenCV", "level": 5},
            {"skill": "TensorFlow", "level": 4},
            {"skill": "PyTorch", "level": 4},
            {"skill": "C++", "level": 4},
            {"skill": "ROS", "level": 3},
            {"skill": "Docker", "level": 3},
            {"skill": "Linux", "level": 4},
            {"skill": "CUDA", "level": 3},
            {"skill": "AWS", "level": 3},
        ],
        "themes": ["Computer Vision", "Robotics"],
    },
]

users.delete_many({})
users.insert_many(data)

print("Data inserted successfully.")

for user in users.find():
    print(user)
